name: Docker SBOM Scanner
description: A Software Bill of Materials scanner
inputs:
  image:
    description: Docker image for the scan
    required: true
runs:
  using: docker
  image: Dockerfile
  args: [
    "--docker", "${{ inputs.image }}"
  ]
